version: '3'
services:
  app:
    container_name: xmlsigner
    build: .
    volumes:
      - /opt/certs/keys/private_keys/:/tmp
    image: xmlsigner
    ports:
      - 7000:9181
    links:
      - redis
  redis:
    container_name: redis
    image: redis
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"