      - name: Build with Gradle
        run: ./gradlew build

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ethswitch_ethswitch
            -Dsonar.organization=ethswitch
            -Dsonar.java.binaries=build/classes
